copyfiles:
	cp $(filepath) .

compile-chocolates:
	@echo 'Python solution. Nothing to compile.'

run-chocolates:
	python3 chocolates.py

list-chocolates:
	ls chocolates.py

show-chocolates:
	@echo 'Showing python file chocolates.py'
	cat chocolates.py

compile-concom:
	@echo 'Python solution. Nothing to compile.'

run-concom:
	python3 concom.py

list-concom:
	ls concom.py

show-concom:
	@echo 'Showing python file concom.py'
	cat concom.py
